import { teardown } from "@mui/utils/useIsFocusVisible";
import Head from "next/head";
import { useEffect, useState, useCallback } from "react";

export default function Home() {
    const [pizzas, setPizzas] = useState("");
    const [searchText, setSearchText] = useState(null);
    useState([]);

    useEffect(() => {
        fetch("/api/pizzas")
            .then((res) => {
                return res.json();
            })
            .then((data) => {
                setPizzas(data.pizzas);
            });
    }, []);

    const searchInputHandler = useCallback((event) => {
        setSearchText(event.target.value);
    }, []);

    const finalPizzas = pizzas.filter((pizza) => {
        return pizza.name.includes(searchText);
    });

    return (
        <>
            <Head>
                <title>Web App Workshop</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <input
                    type={"text"}
                    name={"search"}
                    onchange={searchInputHandler}
                />
                <ul>
                    {finalPizzas.map((pizza, index) => {
                        return <li key={index}>{pizza.name}</li>;
                    })}
                </ul>
            </main>
        </>
    );
}
